# Generated by Django 3.0.7 on 2020-08-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charecters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charecter',
            name='class_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='charecter',
            name='race',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='charecter',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charecters.Team'),
        ),
    ]
