# Generated by Django 3.0.7 on 2020-08-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charecters', '0002_auto_20200814_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='charecter',
            name='alignment',
            field=models.CharField(choices=[('good', 'good'), ('evil', 'evil')], default='good', max_length=10),
        ),
        migrations.AddField(
            model_name='charecter',
            name='armor_class',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='charecter',
            name='hit_points',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='charecter',
            name='notes',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='charecter',
            name='orientation',
            field=models.CharField(choices=[('neutral', 'neutral'), ('lawful', 'lawful'), ('chaotic', 'chaotic')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='charecter',
            name='class_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='class'),
        ),
    ]
