# Generated by Django 3.0.7 on 2020-08-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charecters', '0003_auto_20200816_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notes',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
